Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.define "serv" do |service|
    service.vm.box = 'azure'

    service.ssh.private_key_path = '/home/xenahort/ssh/id_rsa'

    service.vm.provider :azure do |azure, override|
      azure.location="eastus"
      azure.resource_group_name="resource_group"
      azure.vm_name="maquinahito5"
      azure.vm_image_urn="Canonical:UbuntuServer:18.04-LTS:latest"

      azure.vm_size = 'Standard_B1s'
      azure.vm_storage_account_type = 'Standard_LRS'

      azure.tenant_id = ENV['AZURE_TENANT_ID']
      azure.client_id = ENV['AZURE_CLIENT_ID']
      azure.client_secret = ENV['AZURE_CLIENT_SECRET']
      azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']
    end

    service.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision.yml"
    end
  end
end
